name: Deploy to UCD Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Load environment configurations
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Add common bin directories to PATH
          export PATH="$HOME/.npm-global/bin:$HOME/.nvm/versions/node/$(node -v)/bin:$PATH"
          export PATH="$HOME/.local/bin:$HOME/.local/share/pnpm:$PATH"
          
          # Create directory if not exists and navigate to it
          mkdir -p ~/document/ezmark-server/ && cd ~/document/ezmark-server/
          
          # Pull the latest changes
          git pull
          
          # Install dependencies
          pnpm install || $HOME/.local/share/pnpm/pnpm install
          
          # Build the project
          pnpm build || $HOME/.local/share/pnpm/pnpm build
          
          # Restart the application using PM2
          pm2 restart ezmark-server || $HOME/.local/bin/pm2 restart ezmark-server || $(which pm2) restart ezmark-server || $HOME/.local/bin/pm2 start ecosystem.config.js --env production