name: Deploy to UCD Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 加载环境配置
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # 添加常用的bin目录到PATH
          export PATH="$HOME/.npm-global/bin:$HOME/.nvm/versions/node/$(node -v)/bin:$PATH"
          export PATH="$HOME/.local/bin:$HOME/.local/share/pnpm:$PATH"
          
          # 如果目录不存在则创建并导航到该目录
          mkdir -p ~/document/ezmark-server/ && cd ~/document/ezmark-server/
          
          # 拉取最新更改
          git pull
          
          # 安装依赖
          pnpm install || $HOME/.local/share/pnpm/pnpm install
          
          # 构建项目
          pnpm build || $HOME/.local/share/pnpm/pnpm build
          
          # 使用PM2重启应用
          pm2 restart ezmark-server || $HOME/.local/bin/pm2 restart ezmark-server || $(which pm2) restart ezmark-server || $HOME/.local/bin/pm2 start ecosystem.config.js 